@startuml
class Edge {
  -from: Node // 起始节点
  -to: Node   // 终止节点
  +Edge(Node, Node)
  +getFrom(): Node
  +setFrom(Node): void
  +getTo(): Node
  +setTo(Node): void
  +equals(Object): boolean
  +hashCode(): int
}

class Relationship {
  -name: String
  -attribute: String
  +Relationship(Node, Node, String, String)
  +Relationship(Node, Node)
  .. Edge <|-- Relationship : extends
}

@enduml